"""empty message

Revision ID: 01ad32086d3b
Revises: 26d25f12ad56
Create Date: 2026-04-19 15:10:44.986733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ad32086d3b'
down_revision: Union[str, Sequence[str], None] = '26d25f12ad56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_metadata', 'RMSE')
    op.drop_column('model_metadata', 'accuracy')
    op.drop_column('model_metadata', 'AUC')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_metadata', sa.Column('AUC', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('model_metadata', sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('model_metadata', sa.Column('RMSE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
