"""empty message

Revision ID: 26d25f12ad56
Revises: e1c71f33b44a
Create Date: 2026-04-19 13:58:36.772210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26d25f12ad56'
down_revision: Union[str, Sequence[str], None] = 'e1c71f33b44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='level_status'), nullable=False))
    op.drop_column('sections', 'user_id')
    op.add_column('training_data', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_column('training_data', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_data', sa.Column('level', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='level_status'), autoincrement=False, nullable=False))
    op.drop_column('training_data', 'user_id')
    op.add_column('sections', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sections', 'level')
    # ### end Alembic commands ###
