"""empty message

Revision ID: 38962681a946
Revises: d2e3b9b03323
Create Date: 2026-04-21 17:27:00.577005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38962681a946'
down_revision: Union[str, Sequence[str], None] = 'd2e3b9b03323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_metadata', sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='level_status'), nullable=False))
    op.drop_constraint(op.f('model_metadata_section_id_fkey'), 'model_metadata', type_='foreignkey')
    op.drop_constraint(op.f('training_data_section_id_fkey'), 'training_data', type_='foreignkey')
    op.create_foreign_key(None, 'model_metadata', 'sections', ['section_id'], ['skill'])
    op.drop_column('sections', 'id')
    op.drop_column('sections', 'level')
    op.create_foreign_key(None, 'training_data', 'sections', ['section_id'], ['skill'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('level', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='level_status'), autoincrement=False, nullable=False))
    op.add_column('sections', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'training_data', type_='foreignkey')
    op.create_foreign_key(op.f('training_data_section_id_fkey'), 'training_data', 'sections', ['section_id'], ['id'])
    op.drop_constraint(None, 'model_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('model_metadata_section_id_fkey'), 'model_metadata', 'sections', ['section_id'], ['id'])
    op.drop_column('model_metadata', 'level')
    # ### end Alembic commands ###
