"""create training_data table

Revision ID: b935fc14ac62
Revises: 
Create Date: 2026-03-28 09:59:11.253756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b935fc14ac62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('p_init', sa.Float(), nullable=False),
    sa.Column('p_transit', sa.Float(), nullable=False),
    sa.Column('p_slip', sa.Float(), nullable=False),
    sa.Column('p_guess', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('AUC', sa.Float(), nullable=True),
    sa.Column('RMSE', sa.Float(), nullable=True),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ques_id', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='level_status'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_data')
    op.drop_table('model_metadata')
    op.drop_table('sections')
    # ### end Alembic commands ###
