"""empty message

Revision ID: e1c71f33b44a
Revises: 94230fd2c0ab
Create Date: 2026-04-13 06:00:53.058649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c71f33b44a'
down_revision: Union[str, Sequence[str], None] = '94230fd2c0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('skill', sa.String(), nullable=False))
    op.drop_column('sections', 'category')
    op.add_column('training_data', sa.Column('problem_id', sa.String(), nullable=False))
    op.add_column('training_data', sa.Column('order_id', sa.DateTime(), nullable=False))
    op.add_column('training_data', sa.Column('correct', sa.Boolean(), nullable=False))
    op.drop_column('training_data', 'is_done')
    op.drop_column('training_data', 'is_correct')
    op.drop_column('training_data', 'ques_id')
    op.drop_column('training_data', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_data', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('training_data', sa.Column('ques_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('training_data', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('training_data', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('training_data', 'correct')
    op.drop_column('training_data', 'order_id')
    op.drop_column('training_data', 'problem_id')
    op.add_column('sections', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sections', 'skill')
    # ### end Alembic commands ###
