version: 2.1

# Khai báo đây là file setup (chạy đầu tiên)
setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          # So sánh sự thay đổi với nhánh main
          base-revision: main
          # File cấu hình chứa pipeline thực sự sẽ chạy tiếp theo
          config-path: .circleci/tutor-service-config.yml
          # Quy tắc mapping: Nếu file trong tutor-service thay đổi -> Bật biến run-tutor-service thành true
          mapping: |
            tutor-service/.* run-tutor-service true
            frontend/.* run-frontend true
            adaptive-learning-service/.* run-adaptive-app true