version: 2.1

# Sử dụng Node orb của CircleCI để quản lý cache và cài đặt nhanh hơn
orbs:
  node: circleci/node@5.0.0

jobs:
  build-and-test:
    docker:
      # Chọn phiên bản Node tương ứng với dự án NestJS của bạn
      - image: cimg/node:22.14.0
    steps:
      - checkout:
          path: ~/project
      # Lệnh này tự động cài đặt npm và quản lý cache cho thư mục node_modules
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/tutor-service
      - run:
          name: Debug Directory & package.json
          command: |
            echo "Thư mục hiện tại đang đứng:"
            pwd
            echo "Danh sách file trong thư mục này:"
            ls -la
            echo "Nội dung file package.json CI đang đọc:"
            cat package.json
      - run:
          name: Chạy Linter
          command: npm run lint
      # - run:
      #     name: Chạy Unit Tests
      #     command: npm run test
      - run:
          name: Generate Prisma Client
          command: npx prisma generate
      - run:
          name: Build ứng dụng NestJS
          command: npm run build

workflows:
  nest-ci-workflow:
    jobs:
      - build-and-test:
          filters:
            # CI sẽ chạy trên mọi nhánh
            branches:
              only:
                - main
                - staging